# This workflow will fecth code on weekly from and sync with my repo

name: Sync from Forked repo
on:
  schedule: # cron time is UTC 
    - cron: "0 0 * * SAT" #  Runs on Every Sat at 2pm PT. Refer https://crontab.guru/every-saturday
  push:
    branches: 
      - main
permissions:
  actions: read # for detecting the Github Actions environment.
jobs:
  syncRepo:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    env:
      FORKED_REPO: "spring-projects/spring-petclinic" # https://github.com/spring-projects/spring-petclinic
      FORKED_REPO_PATH: "forked-spring-petclinic"
      MY_REPO: "krishnamanchikalapudi/spring-petclinic"
      MY_REPO_PATH: "my-spring-petclinic"
    runs-on: ${{ matrix.os }}
    timeout-minutes: 20   # ref  https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#jobsjob_idtimeout-minutes
    steps:
      - name: Checkout Forked-repo ${{ env.FORKED_REPO }}
        uses: actions/checkout@v4 # ref: https://github.com/actions/checkout
        with:
          repository: ${{ env.FORKED_REPO }}
          token: ${{ github.token }}
          ref: main
          path: ${{ env.FORKED_REPO_PATH }}

      - name: Checkout my-repo ${{ env.MY_REPO }}
        uses: actions/checkout@v4 
        with:
          repository: ${{ env.MY_REPO }}
          path: ${{ env.MY_REPO_PATH }}

      - name: list folders
        run: |
          pwd
          ls -lrt .
          ls -lrt ${{ env.FORKED_REPO_PATH }} 
          ls -lrt ${{ env.MY_REPO_PATH }}

      - name: Clean my-repo folders
        run: |
          cd ${{ env.MY_REPO_PATH }}
          rm -rf src/ target/ k8s/ .gradle/ .mvn/
          ls -lrt .

      - name: Copy files from forked-repo to my-repo
        run: |
          cd ${{ env.MY_REPO_PATH }}
          cp ../${{ env.FORKED_REPO_PATH }}/* .
          ls -lrt .

      - name: Copy files from forked-repo to my-repo
        run: |
          cd ${{ env.MY_REPO_PATH }}
          cp -r -f ../${{ env.FORKED_REPO_PATH }}/* .
          ls -lrt .

      - name: Commit files to GitHub
        run: |
          cd ${{ env.MY_REPO_PATH }}
          

      - name: summary
        run: |
          echo "# :copyright: Summary :adhesive_bandage:" >> $GITHUB_STEP_SUMMARY
          echo " " >> $GITHUB_STEP_SUMMARY
          echo " " >> $GITHUB_STEP_SUMMARY
          echo " - Forked code from ${{ env.FORKED_REPO }} " >> $GITHUB_STEP_SUMMARY
          echo " - My repo code ${{ env.MY_REPO }} " >> $GITHUB_STEP_SUMMARY
          
